# Generated by Django 2.2.28 on 2022-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='room number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=30, verbose_name='phone number'),
        ),
    ]
